
server:
  port: 8081
  
  
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/project_users?createDatabaseIfNotExist=true # for real project
#    url: jdbc:h2:mem:testdb # for testing purposes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /resource/** 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
  instance:
    hostname: localhost
    
jwt:
  secret: MB29COdCIQ
  

