
server:
  port: 8085
  
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/project_products?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
     
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
  instance:
    hostname: localhost